### ISSUE TITLE
Specify translation files

### ISSUE THREAD

**Issue by eduardolima93** [jcbvm/i18n-editor#38] opened 2018-01-12 23:55 UTC
Hi,

First of, very nice editor!

Would it be possible to specify the translation jsons instead having to follow the project folder structure? I have an existing project where the i18n jsons are inside the same folder, therefore the editor doesn't find them.

Bests,

**Comment by jcbvm** [comment] 2018-06-20 08:44
This will be part of release 2.0.0 coming soon!

**Comment by jcbvm** [comment] 2018-06-20 10:18
Duplicate of #28

**Closed by jcbvm** 2018-06-20 10:18 UTC
Labels: enhancement
