### ISSUE TITLE
Save translations in en.json / de.json format

### ISSUE THREAD

**Issue by JavanXD** [jcbvm/i18n-editor#31] opened 2017-09-05 12:47 UTC
I am using [ngx-translate](https://github.com/ngx-translate/core) in my Angular2+ App and your i18n-editor looks great but is not conform with the filenameing standards in my Angular App.
The opportunity to change the naming to the selected language would be great.

![grafik](https://user-images.githubusercontent.com/4342160/30061762-f8a675b8-9248-11e7-8593-5a3d3d882a17.png)

**Comment by JavanXD** [comment] 2017-09-05 13:01
## Workaround in Angular:
```
export function createTranslateLoader(http: HttpClient) {
	return new TranslateHttpLoader(http, './assets/i18n/', '/values.json');
}
```
After setting my TranslateLoader in my Angular App to this path it worked but there should be a GUI Option in this i18n-editor to change the folder structure.

**Comment by jcbvm** [comment] 2017-11-20 09:47
This will be coming in the next release.

**Comment by ndrake** [comment] 2018-03-26 17:04
Any ideas on when the next release will be ready?

**Comment by hadikcz** [comment] 2018-05-22 08:20
So, when will be next release ?

**Comment by jcbvm** [comment] 2018-06-20 08:49
Next release is coming this week

**Comment by jcbvm** [comment] 2018-06-20 10:17
Duplicate of #28

**Closed by jcbvm** 2018-06-20 10:17 UTC
Labels: enhancement
